
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: 
    server: 
  name: 

users:
- name: 
  user:
    as-user-extra: {}
    token: 

contexts:
- context:
    cluster: 
    namespace: 
    user: 
  name: 

current-context: 
