apiVersion: v1
kind: Service
metadata:
  name: service
  annotations: 
spec:
  selector:
    app: app
  sessionAffinity: None
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 8083
    targetPort: 8083