apiVersion: v1
kind: Service
metadata:
  name: service
  annotations: 
    service.beta.kubernetes.io/linode-loadbalancer-throttle: "4"
spec:
  selector:
    app: speechstudio
  sessionAffinity: None
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000